name: Rust

on:
  push:
    branches: [ "master", "passthrough" ]
  pull_request:
    branches: [ "master", "passthrough" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Workflow on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies on ubuntu-latest
      if: runner.os == 'Linux'
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build examples
      run: cargo build --examples
